package com.arbitrier.order.adapter.outbound.kafka;

import com.arbitrier.contracts.common.MessageMetadata;
import com.arbitrier.contracts.common.MoneyAmount;
import com.arbitrier.contracts.common.OrderLineContract;
import com.arbitrier.contracts.order.OrderCreated;
import com.arbitrier.order.domain.event.OrderCreatedDomainEvent;
import com.arbitrier.order.domain.model.OrderLine;
import com.arbitrier.platform.time.TimeProvider;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.UUID;

/**
 * Maps {@link OrderCreatedDomainEvent} to the {@link OrderCreated} Avro contract.
 *
 * <h2>requestedTotal decision (ARB-011)</h2>
 * <p>{@code requestedTotal} is a required field in the {@link OrderCreated} Avro schema but has
 * no equivalent in {@link OrderCreatedDomainEvent}. The domain Order does not model pricing —
 * that remains an open question from ARB-006.
 *
 * <p><strong>Decision (ARB-011, option a):</strong> Emit {@code MoneyAmount("0", "USD")} as a
 * documented placeholder. Downstream consumers must not rely on this value until a pricing source
 * of truth is established and this mapper is updated.
 *
 * <p>OPEN QUESTION: Replace this placeholder when pricing is added to the domain model or when a
 * catalog/pricing service provides the total at order-submission time.
 *
 * <h2>correlationId</h2>
 * <p>{@link OrderCreatedDomainEvent} does not yet carry a {@code correlationId}. The caller
 * (KafkaOrderEventPublisher) reads the correlation ID from the MDC and passes it here.
 * When correlation is threaded through {@code SubmitCorporateBulkOrderCommand}, this parameter
 * should be replaced by the domain event field.
 *
 * <p>Layer: adapter/outbound/kafka
 * <p>Module: order-service
 */
@Component
public class OrderCreatedAvroMapper {

    private static final String SCHEMA_VERSION = "v1";
    private static final String PLACEHOLDER_AMOUNT = "0";
    private static final String PLACEHOLDER_CURRENCY = "USD";

    private final TimeProvider timeProvider;

    public OrderCreatedAvroMapper(final TimeProvider timeProvider) {
        this.timeProvider = timeProvider;
    }

    /**
     * Maps a domain event to an Avro {@link OrderCreated} record.
     *
     * @param event         the domain event produced by {@code Order.create()}
     * @param correlationId business correlation ID — sourced from MDC or generated by the caller
     * @return the Avro contract ready for publishing
     */
    public OrderCreated map(final OrderCreatedDomainEvent event, final String correlationId) {

        final MessageMetadata metadata = MessageMetadata.newBuilder()
                .setMessageId(UUID.randomUUID().toString())
                .setCorrelationId(correlationId)
                .setCausationId(null)
                .setOccurredAt(timeProvider.now().toString())
                .setSchemaVersion(SCHEMA_VERSION)
                .build();

        return OrderCreated.newBuilder()
                .setMetadata(metadata)
                .setOrderId(event.orderId().value())
                .setCustomerId(event.customerId().value())
                .setSubmittedByUserId(event.submittedBy().value())
                .setLines(mapLines(event.lines()))
                .setRequestedTotal(MoneyAmount.newBuilder()
                        .setAmount(PLACEHOLDER_AMOUNT)
                        .setCurrency(PLACEHOLDER_CURRENCY)
                        .build())
                .build();
    }

    private List<OrderLineContract> mapLines(final List<OrderLine> lines) {
        return lines.stream()
                .map(line -> OrderLineContract.newBuilder()
                        .setSku(line.sku().value())
                        .setQuantity(line.quantity().value())
                        .build())
                .toList();
    }
}
