package com.arbitrier.platform.web;

/**
 * HTTP header name constants for correlation propagation across service boundaries.
 *
 * <p>Layer: platform/web
 * <p>Module: platform
 */
public final class CorrelationHeaders {

    /** HTTP request/response header carrying the correlation identifier. */
    public static final String CORRELATION_ID = "X-Correlation-Id";

    /** HTTP response header carrying the per-request identifier generated by the filter. */
    public static final String REQUEST_ID = "X-Request-Id";

    private CorrelationHeaders() {
    }
}
