package com.arbitrier.platform.web;

/**
 * W3C Trace Context HTTP header name constants (RFC 9532 / W3C Recommendation 2021).
 *
 * <p>These headers carry distributed tracing context and are owned by the OpenTelemetry SDK.
 * Application code and platform filters must not generate, overwrite, or remove them.
 *
 * <h2>Header taxonomy</h2>
 * <table border="1">
 *   <caption>Header purposes</caption>
 *   <tr><th>Header</th><th>Owner</th><th>Purpose</th></tr>
 *   <tr><td>{@value #TRACEPARENT}</td><td>OTel SDK (ADR-0008)</td>
 *       <td>Trace ID, parent span ID, sampling flags — technical distributed tracing context</td></tr>
 *   <tr><td>{@value #TRACESTATE}</td><td>OTel SDK (ADR-0008)</td>
 *       <td>Vendor-specific trace state; forwarded unchanged</td></tr>
 *   <tr><td>{@link CorrelationHeaders#CORRELATION_ID}</td><td>{@link CorrelationFilter}</td>
 *       <td>Business-level operation identifier; propagated or generated by the platform filter</td></tr>
 *   <tr><td>{@link CorrelationHeaders#REQUEST_ID}</td><td>{@link CorrelationFilter}</td>
 *       <td>Per-HTTP-request identifier; always generated fresh by the platform filter</td></tr>
 * </table>
 *
 * <p>B3 headers ({@code X-B3-TraceId}, {@code X-B3-SpanId}, {@code X-B3-Sampled}) are not
 * supported as a platform convention. They may only be added at a specific integration boundary
 * where a legacy system requires them, and that boundary must document the exception (ADR-0008).
 *
 * <p>Layer: platform/web
 * <p>Module: platform
 */
public final class TraceContextHeaders {

    /**
     * W3C {@code traceparent} header.
     *
     * <p>Format: {@code 00-<32-hex traceId>-<16-hex parentSpanId>-<8-bit flags>}
     * <br>Example: {@code 00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01}
     */
    public static final String TRACEPARENT = "traceparent";

    /**
     * W3C {@code tracestate} header.
     *
     * <p>Carries optional vendor-specific trace state as a comma-separated list of
     * {@code key=value} pairs. Forwarded unchanged by all intermediaries.
     */
    public static final String TRACESTATE = "tracestate";

    private TraceContextHeaders() {
    }
}
