package com.arbitrier.platform.correlation;

import com.arbitrier.platform.validation.Require;

import java.util.UUID;

/**
 * Identifier for an inbound HTTP request, typically sourced from the {@code X-Request-Id} header.
 *
 * <p>Generated by API gateways or clients and propagated through REST adapters.
 * Used in MDC as {@link com.arbitrier.platform.logging.StructuredLogFields#REQUEST_ID}.
 */
public record RequestId(String value) {

    /** Validates that the value is not blank. */
    public RequestId {
        Require.notBlank(value, "RequestId.value");
    }

    /**
     * Generates a new random {@code RequestId}.
     *
     * @return a new {@code RequestId} backed by a random UUID
     */
    public static RequestId generate() {
        return new RequestId(UUID.randomUUID().toString());
    }

    /**
     * Wraps an existing string value.
     *
     * @param value the raw string; must not be blank
     * @return a {@code RequestId} wrapping {@code value}
     */
    public static RequestId of(String value) {
        return new RequestId(value);
    }

    /** Returns the raw string value — safe for logging (no PII). */
    @Override
    public String toString() {
        return value;
    }
}
